export const DIAS = {
  1:  { titulo:'O Conflito por Dentro',     fase:'A Mente',       faseColor:'#D85A30', desc:'O sofrimento não nasce dos fatos e sim da briga por dentro com o que é. Quando pensamos que algo não deveria estar acontecendo, perdemos 100% das vezes.',                                                                      indez:'Identifique UM pensamento com o qual você está em conflito agora mesmo. Escreva-o sem julgamento.' },
  2:  { titulo:'A Pergunta que Muda Tudo',  fase:'A Mente',       faseColor:'#D85A30', desc:'A dúvida sistemática liberta: isso é verdade? O corpo reage a pensamentos como se fossem reais. A mente cria estresse ou cura.',                                                                                                  indez:'Escolha um pensamento e pergunte: isso é absolutamente verdade? Escreva o que surgiu.' },
  3:  { titulo:'As 4 Perguntas',            fase:'A Mente',       faseColor:'#D85A30', desc:'O método de Byron Katie: 1. Isso é verdade? 2. Você pode saber com certeza absoluta? 3. Como você reage quando acredita nisso? 4. Quem seria você sem esse pensamento?',                                                           indez:'Aplique as 4 perguntas no pensamento de ontem. Anote cada resposta.' },
  4:  { titulo:'O Poder da Inversão',       fase:'A Mente',       faseColor:'#D85A30', desc:'O oposto de um pensamento estressante pode ser tão verdadeiro quanto a dor original — e devolve o poder de ação para você.',                                                                                                        indez:'Inverta o pensamento estressante e encontre 3 exemplos reais da inversão na sua vida.' },
  5:  { titulo:'Você Nunca Está Sozinho(a)',fase:'O Sistema',     faseColor:'#3B6D11', desc:'Nós não entramos em nenhum lugar sozinhos. Carregamos nosso sistema familiar — suas potências e emaranhamentos.',                                                                                                                    indez:'Escreva o nome de 3 ancestrais que fazem parte de você, mesmo sem tê-los conhecido. O que eles trouxeram para a sua história?' },
  6:  { titulo:'Educação Começa em Casa',   fase:'O Sistema',     faseColor:'#3B6D11', desc:'A cura da ferida materna permite que a mulher pare de esperar permissão para viver e se torne autêntica.',                                                                                                                           indez:'Escreva uma frase de gratidão para sua mãe — mesmo que a relação seja complexa.' },
  7:  { titulo:'O Corpo Participa',         fase:'O Corpo',       faseColor:'#185FA5', desc:'O trauma e as crenças deixam registros somáticos. A biologia responde à nova ordem estabelecida na mente.',                                                                                                                          indez:'Observe onde no corpo você sente o pensamento que pesa. Respire nesse lugar por 3 minutos e escreva o que percebeu.' },
  8:  { titulo:'A Névoa que Passa',         fase:'O Corpo',       faseColor:'#185FA5', desc:'A realidade é sempre mais gentil do que a história que contamos sobre ela. O que nubla sua visão pode ser dissolvido.',                                                                                                              indez:'Identifique UM hábito de pensamento que mais nubla sua visão hoje. Como seria sua vida sem ele?' },
  9:  { titulo:'O Toque de Tistu',          fase:'O Corpo',       faseColor:'#185FA5', desc:'A presença consciente tem o poder de transformar ambientes áridos. Onde você toca com clareza, nasce algo novo.',                                                                                                                    indez:'Escolha um ambiente difícil na sua vida e faça UM gesto de presença nele hoje. Conte o que fez.' },
  10: { titulo:'O Algoritmo do Universo',   fase:'A Manifestação',faseColor:'#C8952A', desc:'O universo responde a movimentos pequenos e consistentes. O Indez sinaliza que a vida pode brotar aqui.',                                                                                                                           indez:'Qual é o sinal que você vai dar ao universo hoje? Escreva com clareza.' },
  11: { titulo:'Protocolo de 24 Horas',     fase:'A Manifestação',faseColor:'#C8952A', desc:'Defina uma ação mínima e prática a ser realizada em até 24 horas. Ela mostra que você assumiu sua autoria.',                                                                                                                         indez:'Escreva sua ação de 24h. Comprometa-se agora.' },
  12: { titulo:'O Universo do Sim',         fase:'A Manifestação',faseColor:'#C8952A', desc:'Assentir — aceitar plenamente. O universo amplifica aquilo que você decide começar. Você chegou. Celebre e convide.',                                                                                                               indez:'Escreva a história dos seus 12 dias em 3 frases. O que mudou? O que você plantou? O que floresce agora?' },
}

export const EMOJIS = [null,'🎒','🔍','❓','🔄','🌳','🏠','🫀','🌫️','🌸','🥚','⏰','🌟']

export const FC = {1:'f1',2:'f1',3:'f1',4:'f1',5:'f2',6:'f2',7:'f3',8:'f3',9:'f3',10:'f4',11:'f4',12:'f4'}

export const EDGE_URL = 'https://xfniavcbswqapietgjbe.supabase.co/functions/v1/anthropic-proxy'
export const MODELO   = 'claude-sonnet-4-5'
